### ISSUE TITLE
特定のlabelをクリックする異なるcheckboxがチェックされるバグ

### ISSUE THREAD

**Issue by umezaki1212** [tanjoin/twitter-mute-buzzhuff#4]
キーワード（試用）の韓国と中国の項目にて、lableのfor属性がword_BTSとなっているため、labelをクリックしても異なるcheckboxがチェックされるようです
修正の[プルリクエスト](https://github.com/tanjoin/twitter-mute-buzzhuff/pull/3)を作成しました
お手すきの際に、ご確認いただければと思います

**Comment by tanjoin** [comment]
指摘ありがとうございました
