### ISSUE TITLE
mobile.twitter.com でも使用したい

### ISSUE THREAD

**Issue by genepine** [tanjoin/twitter-mute-buzzhuff#7]
こんにちは
現状、twitter-mute-buzzhuff が有効になるのは twitter.com のみです。
わたしは mobile.twitter.com をPCで使用しています。理由は、左サイドバーのメニューがアイコンのみで、ツイート欄の表示が大きいからです。
 mobile.twitter.com を開き、twitter-mute-buzzhuff を使用するとドロップダウンメニューで使用できない旨のメッセージが出ています。
![Image_20211028_164608](https://user-images.githubusercontent.com/40847696/139212448-8fbe2146-f59d-44eb-ba0e-e8d68263922a.png)

twitter.com でのtwitter-mute-buzzhuffを利用した表示はとても良いので、できましたら  mobile.twitter.com でも使用できるようにしていただけるとありがたいです。

**Comment by tanjoin** [comment]
mobile.twitter.com のPC利用は盲点でした
そこまで大変じゃないと思うのでやってみます

**Comment by tanjoin** [comment]
https://github.com/tanjoin/twitter-mute-buzzhuff/commit/c050e755e4c772d75d8c1c0db680bc7964e21640#diff-6bc2c0b5164076a1b57b067398be19a40d2b8efa3428b03504562ea88593866cR16

対応しました

Ver. 0.5.4 に更新すると動作すると思います
問題があればまた連絡ください

**Comment by genepine** [comment]
早速、ご対応いただきありがとうございます。 mobile.twitter.com  とても見やすくなりました。
